version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persistent volume

volumes:
  postgres_data:  # Define persistent volume for PostgreSQL
  redis_data:     # Define persistent volume for Redis
